pipeline {
    agent any

    environment {
        IMAGE_NAME = "trustretail-ai"
        CONTAINER_NAME = "trustretail-app"
        PORT = "3000"
        VITE_GEMINI_API_KEY = credentials('gemini-api-key')
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Manoghna2005/trustretail-ai.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat """
                docker build ^
                --build-arg VITE_GEMINI_API_KEY=%VITE_GEMINI_API_KEY% ^
                -t %IMAGE_NAME% .
                """
            }
        }

        stage('Stop Old Container') {
            steps {
                bat """
                docker rm -f %CONTAINER_NAME% || exit 0
                """
            }
        }

        stage('Run New Container') {
            steps {
                bat """
                docker run -d ^
                --name %CONTAINER_NAME% ^
                -p %PORT%:80 ^
                %IMAGE_NAME%
                """
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}